src/Entity/Type.php
<?php

namespace App\Entity;

use App\Repository\TypeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TypeRepository::class)
 */
class Type
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $type_description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type_thumbnail;

    /**
     * @ORM\ManyToMany(targetEntity=Game::class, mappedBy="game_type")
     */
    private $games;

    public function __construct()
    {
        $this->games = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeTitle(): ?string
    {
        return $this->type_title;
    }

    public function setTypeTitle(string $type_title): self
    {
        $this->type_title = $type_title;

        return $this;
    }

    public function getTypeDescription(): ?string
    {
        return $this->type_description;
    }

    public function setTypeDescription(?string $type_description): self
    {
        $this->type_description = $type_description;

        return $this;
    }

    public function getTypeThumbnail(): ?string
    {
        return $this->type_thumbnail;
    }

    public function setTypeThumbnail(?string $type_thumbnail): self
    {
        $this->type_thumbnail = $type_thumbnail;

        return $this;
    }

    /**
     * @return Collection|Game[]
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Game $game): self
    {
        if (!$this->games->contains($game)) {
            $this->games[] = $game;
            $game->addGameType($this);
        }

        return $this;
    }

    public function removeGame(Game $game): self
    {
        if ($this->games->removeElement($game)) {
            $game->removeGameType($this);
        }

        return $this;
    }
}

src/Form/TypeType.php
<?php

namespace App\Form;

use App\Entity\Type;
use App\Entity\Game;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\Image;
class TypeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('type_title')
            ->add('type_description')
            ->add('type_thumbnail', FileType::class, [
                'label'=> 'type image',
                'required'   => true,
                'data_class' => NULL,
                'constraints' => [
                    new File([
                        'maxSize' => '5M',
                        'mimeTypes' => [
                            'image/*',
                            'application/pdf',
                            'application/x-pdf',
                        ],
                        'mimeTypesMessage' => 'Le fichier n\'est pas valide, assurez vous d\'avoir un fichier au format PDF, PNG, JPG, JPEG)',
                    ]),
                ]
            ])

            ->add('games',  EntityType::class, [
                'class' => Game::class,
                'choice_label' => 'game_title',
                'multiple' => true,
                'expanded' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Type::class,
        ]);
    }
}

src/Controller/TypeController.php
<?php

namespace App\Controller;

use App\Entity\Type;
use App\Form\TypeType;
use App\Repository\TypeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

#[Route('/type')]
class TypeController extends AbstractController
{
    #[Route('/', name: 'type_index', methods: ['GET'])]
    public function index(TypeRepository $typeRepository): Response
    {
        return $this->render('type/index.html.twig', [
            'types' => $typeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'type_new', methods: ['GET','POST'])]
    public function new(Request $request, SluggerInterface $slugger): Response
    {
        $type = new Type();
        $form = $this->createForm(TypeType::class, $type);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

/** @var UploadedFile $imageType */
$imageType = $form->get('type_thumbnail')->getData();
 
// this condition is needed because the 'imageType' field is not required
// so the PDF/JPG/PNG file must be processed only when a file is uploaded
if ($imageType) {
    $originalFilename = pathinfo($imageType->getClientOriginalName(), PATHINFO_FILENAME);
    // this is needed to safely include the file name as part of the URL
    $safeFilename = $slugger->slug($originalFilename);
    $newFilename = $safeFilename.'-'.uniqid().'.'.$imageType->guessExtension();

    // Move the file to the directory where images are stored
    try {
        $imageType->move(
            $this->getParameter('images_directory_type'),
            $newFilename
        );
    } catch (FileException $e) {
        // ... handle exception if something happens during file upload
    }

    // updates the 'imageTypename' property to store the PDF/JPG/PNG file name
    // instead of its contents
    $type->setTypeThumbnail($newFilename);
}


            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($type);
            $entityManager->flush();

            return $this->redirectToRoute('type_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('type/new.html.twig', [
            'type' => $type,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'type_show', methods: ['GET'])]
    public function show(Type $type): Response
    {
        return $this->render('type/show.html.twig', [
            'type' => $type,
        ]);
    }

    #[Route('/{id}/edit', name: 'type_edit', methods: ['GET','POST'])]
    public function edit(Request $request, Type $type): Response
    {
        $form = $this->createForm(TypeType::class, $type);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('type_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('type/edit.html.twig', [
            'type' => $type,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'type_delete', methods: ['POST'])]
    public function delete(Request $request, Type $type): Response
    {
        if ($this->isCsrfTokenValid('delete'.$type->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($type);
            $entityManager->flush();
        }

        return $this->redirectToRoute('type_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/type/_delete_form.html.twig
<form method="post" action="{{ path('type_delete', {'id': type.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ type.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/type/_form.html.twig
{{ form_start(form) }}
 
<div class="title-group">
    <div>{{form_label(form.type_title)}}</div>
    <div>{{form_widget(form.type_title)}}</div>
</div>

<div class="description-group">
    <div>{{form_label(form.type_description)}}</div>
    <div>{{form_widget(form.type_description)}}</div>
</div>

<div class="image-group">
    <div>{{form_label(form.type_thumbnail)}}</div>
    <div>{{form_widget(form.type_thumbnail)}}</div>
    <td>  {{ type.typeThumbnail }}<img src="{{ asset('uploads/images/type/' ~ type.typeThumbnail) }}" width='125' height='80' ></td>
</div>

<div class="game-group">
    <div>{{form_label(form.games)}}</div>
    <div>{{form_widget(form.games)}}</div>        
</div>

<button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/type/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Type{% endblock %}

{% block body %}
<div class="container">
    <h1>Edit Type</h1>

    {{ include('type/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('type_index') }}">back to list</a>

    {{ include('type/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/type/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Type index{% endblock %}

{% block body %}
<div class="container">
    <h1>Type index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Type_title</th>
                <th>Type_description</th>
                <th>Type_thumbnail</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for type in types %}
            <tr>
                <td>{{ type.id }}</td>
                <td>{{ type.typeTitle }}</td>
                <td>{{ type.typeDescription }}</td>
               <td>  <img src="{{ asset('uploads/images/type/' ~ type.typeThumbnail) }}" alt="{{ type.typeThumbnail }}" width='125' height='80' ></td>
                <td>
                    <a href="{{ path('type_show', {'id': type.id}) }}">show</a>
                    <a href="{{ path('type_edit', {'id': type.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('type_new') }}">Create new</a>
</div>
{% endblock %}

templates/type/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Type{% endblock %}

{% block body %}
<div class="container">
    <h1>Create new Type</h1>

    {{ include('type/_form.html.twig') }}

    <a href="{{ path('type_index') }}">back to list</a>
</div>
{% endblock %}

templates/type/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Type{% endblock %}

{% block body %}
<div class="container">
    <h1>Type</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ type.id }}</td>
            </tr>
            <tr>
                <th>Type_title</th>
                <td>{{ type.typeTitle }}</td>
            </tr>
            <tr>
                <th>Type_description</th>
                <td>{{ type.typeDescription }}</td>
            </tr>
            <tr>
                <th>Type_thumbnail</th>
                <td>{{ type.typeThumbnail }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('type_index') }}">back to list</a>

    <a href="{{ path('type_edit', {'id': type.id}) }}">edit</a>

    {{ include('type/_delete_form.html.twig') }}.
</div>
{% endblock %}