src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $comment_content;

    /**
     * @ORM\Column(type="integer")
     */
    private $comment_rate;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $comment_createAt;

    /**
     * @ORM\ManyToOne(targetEntity=Game::class, inversedBy="comments")
     */
    private $comment_game;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     */
    private $comment_user;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentContent(): ?string
    {
        return $this->comment_content;
    }

    public function setCommentContent(string $comment_content): self
    {
        $this->comment_content = $comment_content;

        return $this;
    }

    public function getCommentRate(): ?int
    {
        return $this->comment_rate;
    }

    public function setCommentRate(int $comment_rate): self
    {
        $this->comment_rate = $comment_rate;

        return $this;
    }

    public function getCommentCreateAt(): ?\DateTimeImmutable
    {
        return $this->comment_createAt;
    }

    public function setCommentCreateAt(\DateTimeImmutable $comment_createAt): self
    {
        $this->comment_createAt = $comment_createAt;

        return $this;
    }

    public function __construct() {
        $this->comment_createAt = new \DateTimeImmutable();
    }

    public function getCommentGame(): ?Game
    {
        return $this->comment_game;
    }

    public function setCommentGame(?Game $comment_game): self
    {
        $this->comment_game = $comment_game;

        return $this;
    }

    public function getCommentUser(): ?User
    {
        return $this->comment_user;
    }

    public function setCommentUser(?User $comment_user): self
    {
        $this->comment_user = $comment_user;

        return $this;
    }

}

src/Entity/Game.php
<?php

namespace App\Entity;

use App\Repository\GameRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GameRepository::class)
 */
class Game
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $game_title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $game_url;

    /**
     * @ORM\Column(type="text")
     */
    private $game_description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $game_thumbnail;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $game_rating;

    /**
     * @ORM\ManyToMany(targetEntity=Type::class, inversedBy="games")
     */
    private $game_type;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="comment_game")
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="game_user")
     */
    private $users;

    public function __construct()
    {
        $this->game_type = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGameTitle(): ?string
    {
        return $this->game_title;
    }

    public function setGameTitle(string $game_title): self
    {
        $this->game_title = $game_title;

        return $this;
    }

    public function getGameUrl(): ?string
    {
        return $this->game_url;
    }

    public function setGameUrl(string $game_url): self
    {
        $this->game_url = $game_url;

        return $this;
    }

    public function getGameDescription(): ?string
    {
        return $this->game_description;
    }

    public function setGameDescription(string $game_description): self
    {
        $this->game_description = $game_description;

        return $this;
    }

    public function getGameThumbnail(): ?string
    {
        return $this->game_thumbnail;
    }

    public function setGameThumbnail(?string $game_thumbnail): self
    {
        $this->game_thumbnail = $game_thumbnail;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeImmutable $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getGameRating(): ?string
    {
        return $this->game_rating;
    }

    public function setGameRating(?string $game_rating): self
    {
        $this->game_rating = $game_rating;

        return $this;
    }

    /**
     * @return Collection|Type[]
     */
    public function getGameType(): Collection
    {
        return $this->game_type;
    }

    public function addGameType(Type $gameType): self
    {
        if (!$this->game_type->contains($gameType)) {
            $this->game_type[] = $gameType;
        }

        return $this;
    }

    public function removeGameType(Type $gameType): self
    {
        $this->game_type->removeElement($gameType);

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setCommentGame($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getCommentGame() === $this) {
                $comment->setCommentGame(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addGameUser($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeGameUser($this);
        }

        return $this;
    }
}

src/Entity/Type.php
<?php

namespace App\Entity;

use App\Repository\TypeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TypeRepository::class)
 */
class Type
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $type_description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type_thumbnail;

    /**
     * @ORM\ManyToMany(targetEntity=Game::class, mappedBy="game_type")
     */
    private $games;

    public function __construct()
    {
        $this->games = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeTitle(): ?string
    {
        return $this->type_title;
    }

    public function setTypeTitle(string $type_title): self
    {
        $this->type_title = $type_title;

        return $this;
    }

    public function getTypeDescription(): ?string
    {
        return $this->type_description;
    }

    public function setTypeDescription(?string $type_description): self
    {
        $this->type_description = $type_description;

        return $this;
    }

    public function getTypeThumbnail(): ?string
    {
        return $this->type_thumbnail;
    }

    public function setTypeThumbnail(?string $type_thumbnail): self
    {
        $this->type_thumbnail = $type_thumbnail;

        return $this;
    }

    /**
     * @return Collection|Game[]
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Game $game): self
    {
        if (!$this->games->contains($game)) {
            $this->games[] = $game;
            $game->addGameType($this);
        }

        return $this;
    }

    public function removeGame(Game $game): self
    {
        if ($this->games->removeElement($game)) {
            $game->removeGameType($this);
        }

        return $this;
    }
}

src/Form/GameType.php
<?php

namespace App\Form;

use App\Entity\Comment;
use App\Entity\Game;
use App\Entity\Type;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class GameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('game_title')
            ->add('game_url')
            ->add('game_description')
            ->add('game_thumbnail', FileType::class, [
                'label'=> 'game image',
                'required'   => true,
                'data_class' => NULL,
                'constraints' => [
                    new File([
                        'maxSize' => '5M',
                        'mimeTypes' => [
                            'image/*',
                        ],
                        'mimeTypesMessage' => 'Le fichier n\'est pas valide, assurez vous d\'avoir un fichier au format PNG, JPG, JPEG)',
                    ]),
                ]
                ])

            ->add('game_type', EntityType::class, [
                'class' => Type::class,
                'choice_label' => 'type_title',
                'multiple' => true,
                'expanded' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Game::class,
        ]);
    }
}

src/Controller/GameController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Game;
use App\Entity\User;
use App\Form\GameType;
use DateTimeImmutable;
use App\Entity\Comment;
use App\Form\CommentType;
use App\Repository\GameRepository;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

#[Route('/game')]
class GameController extends AbstractController
{
    #[IsGranted('ROLE_ADMIN')]
    #[Route('/', name: 'game_index', methods: ['GET'])]
    public function index(GameRepository $gameRepository): Response
    {
        return $this->render('game/index.html.twig', [
            'games' => $gameRepository->findAll(),
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/new', name: 'game_new', methods: ['GET','POST'])]
    public function new(Request $request, SluggerInterface $slugger): Response
    {
        $game = new Game();
        $game->setCreateAt(new DateTimeImmutable('now'));
        $form = $this->createForm(GameType::class, $game);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

             /** @var UploadedFile $imageType */
             $imageGame = $form->get('game_thumbnail')->getData();
 
             // this condition is needed because the 'imageType' field is not required
             // so the PDF/JPG/PNG file must be processed only when a file is uploaded
             if ($imageGame) {
                 $originalFilename = pathinfo($imageGame->getClientOriginalName(), PATHINFO_FILENAME);
                 // this is needed to safely include the file name as part of the URL
                 $safeFilename = $slugger->slug($originalFilename);
                 $newFilename = $safeFilename.'-'.uniqid().'.'.$imageGame->guessExtension();
  
                 // Move the file to the directory where images are stored
                 try {
                     $imageGame->move(
                         $this->getParameter('images_directory_game'),
                         $newFilename
                     );
                 } catch (FileException $e) {
                     // ... handle exception if something happens during file upload
                 }
  
                 // updates the 'imageTypename' property to store the PDF/JPG/PNG file name
                 // instead of its contents
                 $game->setGameThumbnail($newFilename);
             }
             

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($game);
            $entityManager->flush();

            return $this->redirectToRoute('game_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('game/new.html.twig', [
            'game' => $game,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'game_show', methods: ['GET','POST'])]
    public function show(Game $game, Request $request): Response
    {   
        $user = $this->getUser();
        $comment = new Comment();
        $gameId = $game->getId();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setCommentCreateAt(new \DateTimeImmutable());
            $comment->setCommentGame($game);
            $comment->setCommentUser($user);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('game_show', ["id" => $gameId], Response::HTTP_SEE_OTHER);
        }


        return $this->render('game/show.html.twig', [
            'game' => $game,
            'commentForm' => $form->createView(),
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/{id}/edit', name: 'game_edit', methods: ['GET','POST'])]
    public function edit(Request $request, Game $game, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(GameType::class, $game);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageType */
            $imageGame = $form->get('game_thumbnail')->getData();
 
            // this condition is needed because the 'imageType' field is not required
            // so the PDF/JPG/PNG file must be processed only when a file is uploaded
            if ($imageGame) {
                $originalFilename = pathinfo($imageGame->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$imageGame->guessExtension();
 
                // Move the file to the directory where images are stored
                try {
                    $imageGame->move(
                        $this->getParameter('images_directory_game'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
 
                // updates the 'imageTypename' property to store the PDF/JPG/PNG file name
                // instead of its contents
                $game->setGameThumbnail($newFilename);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('game_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('game/edit.html.twig', [
            'game' => $game,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/{id}', name: 'game_delete', methods: ['POST'])]
    public function delete(Request $request, Game $game): Response
    {
        if ($this->isCsrfTokenValid('delete'.$game->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($game);
            $entityManager->flush();
        }

        return $this->redirectToRoute('game_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/game/_delete_form.html.twig
<form method="post" action="{{ path('game_delete', {'id': game.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ game.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/game/_form.html.twig
{{ form_start(form) }}
 
    <div class="title-group">
        <div>{{form_label(form.game_title)}}</div>
        <div>{{form_widget(form.game_title)}}</div>
    </div>
 
    <div class="description-group">
        <div>{{form_label(form.game_description)}}</div>
        <div>{{form_widget(form.game_description)}}</div>
    </div>

    <div class="url-group">
        <div>{{form_label(form.game_url)}}</div>
        <div>{{form_widget(form.game_url)}}</div>
    </div>
 
    <div class="image-group">
        <div>{{form_label(form.game_thumbnail)}}</div>
        <div>{{form_widget(form.game_thumbnail)}}</div>
        <img src="{{ asset('uploads/images/game/' ~ game.gameThumbnail) }}" alt="{{ game.gameThumbnail }}" width='125' height='80' >
    </div>
    
    <div class="type-group">
        <div>{{form_label(form.game_type)}}<br/></div>
        <div>{{form_widget(form.game_type)}}</div>
    </div>
 
 
    <button type="submit" class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/game/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Game{% endblock %}

{% block body %}
<div class="container">
    <h1>Edit Game</h1>

    {{ include('game/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('game_index') }}">back to list</a>

    {{ include('game/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/game/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Game index{% endblock %}

{% block body %}
<div class="container">
    <h1>Game index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Game_title</th>
                <th>Game_url</th>
                <th>Game_description</th>
                <th>Game_thumbnail</th>
                <th>CreateAt</th>
                <th>Game_rating</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for game in games %}
            <tr>
                <td>{{ game.id }}</td>
                <td>{{ game.gameTitle }}</td>
                <td>{{ game.gameUrl }}</td>
                <td>{{ game.gameDescription }}</td>
                <td><img src="{{ asset('uploads/images/game/' ~ game.gameThumbnail) }}" alt="{{ game.gameThumbnail }}" width='125' height='80' ></td>
                <td>{{ game.createAt ? game.createAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ game.gameRating }}</td>
                <td>
                    <a href="{{ path('game_show', {'id': game.id}) }}">show</a>
                    <a href="{{ path('game_edit', {'id': game.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('game_new') }}">Create new</a>
</div>
{% endblock %}

templates/game/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Game{% endblock %}

{% block body %}
<div class="container">
    <h1>Create new Game</h1>

    {{ include('game/_form.html.twig') }}

    <a href="{{ path('game_index') }}">back to list</a>
</div>
{% endblock %}

templates/game/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Game
{% endblock %}

{% block body %}
{% if is_granted('ROLE_ADMIN') %}
<div class="container">
    <h1>Game</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ game.id }}</td>
            </tr>
            <tr>
                <th>Game_title</th>
                <td>{{ game.gameTitle }}</td>
            </tr>
            <tr>
                <th>Game_url</th>
                <td><a href="{{ game.gameUrl }}" target="_blank">{{ game.gameUrl }}</a></td>
            </tr>
            <tr>
                <th>Game_description</th>
                <td>{{ game.gameDescription }}</td>
            </tr>
            <tr>
                <th>Game</th>
                <td><img src="{{ asset('uploads/images/game/' ~ game.gameThumbnail) }}" alt="{{ game.gameThumbnail }}"
                        width='125' height='80'></td>
            </tr>
            <tr>
                <th>CreateAt</th>
                <td>{{ game.createAt ? game.createAt|date('d/m/Y') : '' }}</td>
            </tr>
            <tr>
                <th>Game_rating</th>
                <td>{{ game.gameRating }}</td>
            </tr>
        </tbody>
    </table>
    {% for type in game.gameType %}
    <p>{{type.typeTitle}}</p>
    {% endfor %}

    <h2> {{ game.gameType | length }} genres </h2>
    {% for type in game.gameType %}
    <p><strong>Genre</strong> : {{type.typeTitle}}</p>
    {% endfor %}

		<h2>
			{{ game.gameType | length }}
			genres
		</h2>
		{% for type in game.gameType %}
			<p>
				<strong>Genre</strong>
				:
				{{type.typeTitle}}</p>
		{% endfor %}


    <section id="commentaires">
        <h2> {{ game.comments | length }} commentaires </h2>
        {% for comment in game.comments %}
        <pre>
        {{comment.commentContent | raw}}
        {{comment.commentRate}}
        {{comment.commentCreateAt | date("d/m/Y")}}
        {{comment.commentUser.nickname}}
        </pre>
        {% endfor %}

    </section>

    <section id="formComment">
        {{form_start(commentForm)}}
        {{form_row(commentForm.comment_content, {'attr' : {'placeholder' : " votre avis"}})}}
        {{form_row(commentForm.comment_rate, {'attr' : {'placeholder' : " votre note"}})}}



        <button type="submit"> Avis ! </button>
        {{ form_end(commentForm)}}
    </section>


		<a href="{{ path('game_index') }}">back to list</a>

		<a href="{{ path('game_edit', {'id': game.id}) }}">edit</a>

    {{ include('game/_delete_form.html.twig') }}
</div>
{% else %}
<div class="game_info_container">
    <div class="thumb_play">
        <div id="ex1">
            <img id="ex1-layer" src="{{ asset('uploads/images/game/' ~ game.gameThumbnail) }}"
                alt="{{ game.gameThumbnail }}">
        </div>
    </div>
    <div class="game_infos">
            <h2>{{ game.gameTitle }}</h2>
            <div>{{ game.gameRating }}</div>
            <p>{{ game.gameDescription }}</p>
        <div>
            <a id="btn_play" href="{{ game.gameUrl }}" target="_blank">Jouer</a>
        </div>
    </div>
</div>
<section class="comment_form_container" id="commentaires">
    {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
    <div class="container">
        <section id="formComment">
            {{form_start(commentForm)}}
            {{form_row(commentForm.comment_content, {'label' : 'Laisser un commentaire :', 'attr' : {'placeholder' : "Votre commentaire..."}})}}
            {{form_row(commentForm.comment_rate, {'label' : 'Laisser une note :', 'attr' : {'placeholder' : "Votre note..."}})}}
            <button class="send-btn" type="submit">Envoyer !</button>
            {{ form_end(commentForm)}}
        </section>
    </div>
    {% else %}
    <p>Vous devez être <a href="{{ path('app_login') }}">connecté</a> pour laisser un commentaire !</p>
    {% endif %}
    <div class="comment_section">
        <h2> {{ game.comments | length }} Commentaires </h2>
        {% for comment in game.comments %}
        <span class="comm_nickname">{{comment.commentUser.nickname}}</span> le {{comment.commentCreateAt | date("d/m/Y")}} :
        <p>"{{comment.commentContent | raw}}"</p>
        <p>a noté le jeu {{ comment.commentRate }} / 5</p>
        {% endfor %}
    </div>
</section>
{% endif %}
{% endblock %}